stages:
  download-export-monthly-metadata:
    cmd: Rscript stages/download-export-monthly-metadata.R
    deps:
      - stages/download-export-monthly-metadata.R
    outs:
      - metadata/export-monthly/flatfiles/:
          persist: false # true
      - metadata/export-monthly/pgdump/:
          persist: false # true
  download:
    cmd: Rscript stages/download.R
    deps:
    - stages/download.R
    - "https://aact.ctti-clinicaltrials.org/pipe_files"
    outs:
    - download/
  download-metadata:
    cmd: stages/download-metadata.sh
    deps:
    - stages/download-metadata.sh
    outs:
    - metadata/
  build:
    cmd: Rscript stages/build.R
    deps:
    - stages/build.R
    - download/
    - metadata/
    outs:
    - brick/
